config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :chefs do
    resources :dishes
  end

  namespace :admin do
    resources :orders, only: [:index, :show] do
      member do
        get :report
      end
      collection do
        get :report
        get :cash_flow
      end
    end
  end

  namespace :chef do
    resources :orders, only: [:index] do
      collection do
        put :to_process
        put :finalized
      end
    end
  end

  namespace :cashier do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chef.rb
# == Schema Information
#
# Table name: chefs
#
#  id         :integer          not null, primary key
#  name       :string
#  active     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Chef < ApplicationRecord
  has_one :user, as: :profile, dependent: :destroy
  has_many :dishes
end

app/controllers/chef/orders_controller.rb
class Chef::OrdersController < ApplicationController
  before_action :valid_chef, :authenticate_user!

  before_action :set_order, only: [:finalized, :to_process]

  def index
    @orders = Order.in_command.or(Order.in_processing)
  end

  def to_process
    respond_to do |format|
      if @order.commands? && @order.processing!
        format.html { redirect_to chef_orders_path, notice: 'Order was successfully updated.' }
      else
        format.html { redirect_to chef_orders_path }
      end
    end
  end

  def finalized
    respond_to do |format|
      if @order.processing? && @order.finished!
        format.html { redirect_to chef_orders_path, notice: 'Order was successfully updated.' }
      else
        format.html { redirect_to chef_orders_path }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :valid_admin, :authenticate_user!

  before_action :set_chef, only: [:show, :edit, :update, :destroy]

  # GET /chefs
  # GET /chefs.json
  def index
    @chefs = Chef.all
  end

  # GET /chefs/1
  # GET /chefs/1.json
  def show
  end

  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # GET /chefs/1/edit
  def edit
  end

  # POST /chefs
  # POST /chefs.json
  def create
    @chef = Chef.new(chef_params)

    respond_to do |format|
      if @chef.save
        format.html { redirect_to @chef, notice: 'Chef was successfully created.' }
        format.json { render :show, status: :created, location: @chef }
      else
        format.html { render :new }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chefs/1
  # PATCH/PUT /chefs/1.json
  def update
    respond_to do |format|
      if @chef.update(chef_params)
        format.html { redirect_to @chef, notice: 'Chef was successfully updated.' }
        format.json { render :show, status: :ok, location: @chef }
      else
        format.html { render :edit }
        format.json { render json: @chef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chefs/1
  # DELETE /chefs/1.json
  def destroy
    @chef.destroy
    respond_to do |format|
      format.html { redirect_to chefs_url, notice: 'Chef was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chef
      @chef = Chef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chef_params
      params.fetch(:chef, {})
    end
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/views/chefs/_form.html.erb
<%= form_with(model: chef, local: true) do |form| %>
  <% if chef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chef.errors.count, "error") %> prohibited this chef from being saved:</h2>

      <ul>
      <% chef.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chefs/edit.html.erb
<h1>Editing Chef</h1>

<%= render 'form', chef: @chef %>

<%= link_to 'Show', @chef %> |
<%= link_to 'Back', chefs_path %>

app/views/chefs/index.html.erb
<h1>Chefs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chefs.each do |chef| %>
      <tr>
        <td><%= link_to 'Show', chef %></td>
        <td><%= link_to 'Edit', edit_chef_path(chef) %></td>
        <td><%= link_to 'Destroy', chef, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chef', new_chef_path %>

app/views/chefs/new.html.erb
<h1>New Chef</h1>

<%= render 'form', chef: @chef %>

<%= link_to 'Back', chefs_path %>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chef_path(@chef) %> |
<%= link_to 'Back', chefs_path %>