config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :chefs do
    resources :dishes
  end

  namespace :admin do
    resources :orders, only: [:index, :show] do
      member do
        get :report
      end
      collection do
        get :report
        get :cash_flow
      end
    end
  end

  namespace :chef do
    resources :orders, only: [:index] do
      collection do
        put :to_process
        put :finalized
      end
    end
  end

  namespace :cashier do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  state          :integer          default("commands")
#  payment_method :integer          default("cash")
#  total          :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  customer_id    :integer
#

class Order < ApplicationRecord
  has_many :quantities, inverse_of: :order
  has_many :dishes, through: :quantities
  belongs_to :customer

  enum state: [ :commands, :processing, :finished ]
  enum payment_method: [ :cash, :card ]

  accepts_nested_attributes_for :quantities,
                                :reject_if => :all_blank,
                                :allow_destroy => true
  # accepts_nested_attributes_for :dishes

  scope :in_command, -> { where(state: [:commands]) }
  scope :in_processing, -> { where(state: [:processing]) }
  scope :in_finished, -> { where(state: [:finished]) }
  scope :today, -> { where("created_at BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'") }
  scope :month, -> { where('created_at >= ? AND created_at <= ?', DateTime.now.beginning_of_month, DateTime.now.end_of_month) }
  scope :order_today, -> { order(created_at: :desc).today }


  def update_total
    vartotal = 0
    dishes.each do |dish|
      vartotal = vartotal + dish.price
    end
    self.total =  vartotal
    save!
  end

  def self.cash_flow_today
    today.in_finished.sum(:total)
  end

  def self.cash_flow_month
    month.in_finished.sum(:total)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :valid_admin, :authenticate_user!
  before_action :set_order, only: [:finished]

  def index
    @orders = Order.in_command.or(Order.in_processing)
  end

  def cash_flow
    @orders = Order.in_finished
  end

  # def finished
  #   respond_to do |format|
  #     if @order.update(state: Order.states[:finished])
  #       format.html { redirect_to chef_orders_path, notice: 'Order was successfully updated.' }
  #     else
  #       format.html { redirect_to chef_orders_path }
  #     end
  #   end
  # end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/cashier/orders_controller.rb
class Cashier::OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @order.quantities.build(quantity: 0).build_dish
  end

  def create
    @order = Order.create(order_params)
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end



  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.fetch(:order, {}).permit(:state, :payment_method, :total, :quantities_attributes=>[:quantity, :dish_attributes=> [:id]])
  end


end

app/controllers/chef/orders_controller.rb
class Chef::OrdersController < ApplicationController
  before_action :valid_chef, :authenticate_user!

  before_action :set_order, only: [:finalized, :to_process]

  def index
    @orders = Order.in_command.or(Order.in_processing)
  end

  def to_process
    respond_to do |format|
      if @order.commands? && @order.processing!
        format.html { redirect_to chef_orders_path, notice: 'Order was successfully updated.' }
      else
        format.html { redirect_to chef_orders_path }
      end
    end
  end

  def finalized
    respond_to do |format|
      if @order.processing? && @order.finished!
        format.html { redirect_to chef_orders_path, notice: 'Order was successfully updated.' }
      else
        format.html { redirect_to chef_orders_path }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end
end

app/views/admin/orders/_tables_orders.html.erb
<div id="tab1" class="col s12">
  <table responsive-tableclass="responsive-table">
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <thead>
    <tr>
      <th> Correo</th>
      <th>Status</th>
      <th>Payment method</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @orders.today.each do |order| %>
        <tr>
          <td><%=order.customer.user.email%> </td>
          <td><%=order.state%></td>
          <td><%=order.payment_method%></td>
          <td>$<%=order.total%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div>
    <h3>Total today: <%= Order.cash_flow_today %></h3>
  </div>
</div>

<div id="tab2" class="col s12 ">
  <table class="responsive-table">
    <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
    </thead>

    <thead>
    <tr>
      <th> Correo</th>
      <th>Status</th>
      <th>Payment method</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @orders.month.each do |order| %>
        <tr>
          <td><%=order.customer.user.email%> </td>
          <td><%=order.state%></td>
          <td><%=order.payment_method%></td>
          <td>$<%=order.total%></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div>
    <h3>Total month: <%= Order.cash_flow_month %></h3>
  </div>
</div>

app/views/admin/orders/cash_flow.html.erb
<div class="row">
  <div class="col s12">
    <ul class="tabs tabs-fixed-width ">
      <li class="tab col s3 "><a href="#tab1" class = "active teal-text ">Today</a></li>
      <li class="tab col s3"><a href="#tab2" class = "teal-text">Month</a></li>
    </ul>
  </div>
  <%=render "admin/orders/tables_orders"%>
</div>

app/views/admin/orders/index.html.erb
<h1>Orders</h1>
<%= link_to 'Generate Report', '#' %>

<table>
  <thead>
  <tr>
    <th colspan="3"></th>
  </tr>
  </thead>

  <thead>
  <tr>
    <th> Correo</th>
    <th>Status</th>
    <th>Total</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
      <tr>
        <td><%=order.customer.user.email%> </td>
        <td><%=order.state%></td>
        <td><%=order.total%></td>
        <td><%= link_to 'Show', admin_order_path(id: order) %></td>
      </tr>
  <% end %>
  </tbody>

</table>

app/views/admin/orders/show.html.erb
<h1>Show</h1>
<%= link_to 'Generate Report', '#' %>