config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :chefs do
    resources :dishes
  end

  namespace :admin do
    resources :orders, only: [:index, :show] do
      member do
        get :report
      end
      collection do
        get :report
        get :cash_flow
      end
    end
  end

  namespace :chef do
    resources :orders, only: [:index] do
      collection do
        put :to_process
        put :finalized
      end
    end
  end

  namespace :cashier do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_logout.html.erb
<% unless current_user.nil? %>
    <ul id="dropdown1" class="dropdown-content">
      <li><a href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a></li>
    </ul>
    <nav>
      <div class="nav-wrapper teal ">
        <a href="#" class="brand-logo center">Logo</a>
        <ul id=" nav-mobile" class="left ">
          <% if current_user.chef? %>
              <li><a href="<%=   chef_dishes_path(chef_id: current_user.profile)%>">Dishes</a></li>
              <li><a href="<%=  chef_orders_path %>">Orders</a></li>
          <%elsif current_user.admin?%>
              <li><a href="<%= admin_orders_path %>">Orders</a></li>
              <li><a href="<%= cash_flow_admin_orders_path %>">CashFlow</a></li>
        <% end%>
        </ul>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%=current_user.email %><i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </nav>
<% end %>

app/views/shared/_messages.html.erb
<% unless notice.blank? %>
	<input id="notif-type" type="hidden" value="success" />
	<input id="notif-msg" type="hidden" value="<%= notice %>" />
	<input id="notif-duration" type="hidden" value="10" />
<% end %>
<% unless alert.blank? %>
	<input id="notif-type" type="hidden" value="alert" />
	<input id="notif-msg" type="hidden" value="<%= alert %>" />
	<input id="notif-duration" type="hidden" value="10" />
<% end %>