config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :chefs do
    resources :dishes
  end

  namespace :admin do
    resources :orders, only: [:index, :show] do
      member do
        get :report
      end
      collection do
        get :report
        get :cash_flow
      end
    end
  end

  namespace :chef do
    resources :orders, only: [:index] do
      collection do
        put :to_process
        put :finalized
      end
    end
  end

  namespace :cashier do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dish.rb
# == Schema Information
#
# Table name: dishes
#
#  id                   :integer          not null, primary key
#  name                 :string
#  description          :text
#  price                :float
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  chef_id              :integer
#  active               :boolean          default(FALSE)
#  picture_file_name    :string
#  picture_content_type :string
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#

class Dish < ApplicationRecord
  has_many :quantities, inverse_of: :dish
  has_many :orders, through: :quantities
  belongs_to :chef

  validates :price, presence: true
  validates :name, presence: true


  has_attached_file :picture, styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: '/imagenes/:style/miss.jpg'

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/


  def my_chef?(chef_)
    chef == chef_ ? true : false
  end

  def active_?
    if active
      'Active'
    else
      'disabled'
    end
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :valid_chef, :authenticate_user!

  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action :set_chef

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = @chef.dishes
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    unless @dish.my_chef?(@chef)
      redirect_to :chef_dishes
    end
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  def create
    @dish = Dish.new(dish_params)
    @dish.chef = @chef
    respond_to do |format|
      if @dish.save
        format.html { redirect_to [@chef, @dish], notice: 'Dish was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /dishes/1

  def update
    respond_to do |format|
      if @dish.my_chef?(@chef)
        if @dish.update(dish_params)
          format.html { redirect_to [@chef, @dish], notice: 'Dish was successfully updated.' }
        else
          format.html { render :edit }
        end
      else
        format.html { redirect_to :chef_dishes }
      end
    end
  end

  # DELETE /dishes/1
  def destroy
    respond_to do |format|
      if @dish.my_chef?(@chef)
        if @dish.active?
          @dish.active = false
        else
          @dish.active = true
        end
        if @dish.save
          format.html { redirect_to :chef_dishes }
        else
          format.html { render :edit }
        end
      else
        format.html { redirect_to :chef_dishes }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    def set_chef
      @chef = Chef.find(params[:chef_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.fetch(:dish, {}).permit(:name, :description, :price, :active, :picture)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
  def circle_img(url, size = 300)
    content_tag(:div, '', class: 'circle cover', style: "height: #{size}px;
          width: #{size}px; background-image: url(#{url});
          box-shadow: 0px 1px 5px #3f51b5;")
  end
end

app/views/dishes/_form.html.erb
<div class = "row">
  <%= form_with(model: [ @chef, @dish ], local: true, class: "col s12") do |form| %>
      <% if dish.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

            <ul>
              <% dish.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="input-field col s12">
        <%= form.label :name %>
        <%= form.text_field :name, required: true %>
      </div>

      <div class="input-field col s12 ">
        <%= form.label :description %>
        <%= form.text_area :description, class: "materialize-textarea" %>
      </div>

      <div class="input-field col s12">
        <%= form.label :price %>
        <br><br>
        <%= form.text_field :price, :type => "decimal", required: true %>
      </div>

      <div class="input-field col s12">
        <%=form.file_field :picture %>
        <br><br>
      </div>


      <%= form.submit "Create Dish", class:"btn btn-large waves-light" %>
  <% end %>
</div>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', chef_dish_path(@chef, @dish) %> |
<%= link_to 'Back', chef_dishes_path(@chef) %>

app/views/dishes/index.html.erb
<h1>Dishes</h1>
<a class="btn-floating btn-large waves-effect waves-light right" href="<%=new_chef_dish_path(@chef)%>"><i class="material-icons">add</i></a>



<table class="responsive-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Dish Price</th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%=dish.name%></td>
        <td><%=dish.description%></td>
        <td>$<%=dish.price%></td>
        <td><%= link_to content_tag('i','edit', class: 'material-icons'), edit_chef_dish_path(@chef, dish) %></td>
        <td><%= link_to content_tag('i','visibility', class: 'material-icons'), chef_dish_path(@chef, dish) %></td>
        <%if dish.active? %>
            <td><%= link_to content_tag('i','check', class: 'material-icons'), [@chef, dish], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
            <td><%= link_to content_tag('i','close', class: 'material-icons'), [@chef, dish], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <%end%>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

app/views/dishes/show.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <div class="card ">
      <div class="card-image waves-effect waves-block waves-light card-margin ">
        <%= circle_img @dish.picture.url(:medium) %>
      </div>
      <div class="card-content center">
        <span class="card-title activator grey-text text-darken-4"><%=@dish.name%><i class="material-icons right">more_vert</i></span>
        <p> <%= link_to 'Edit',  edit_chef_dish_path(@chef, @dish) %> </p>
      </div>
      <div class="card-reveal center">
        <span class="card-title grey-text text-darken-4"><%=@dish.name%><i class="material-icons right">close</i></span>
        <p><%=@dish.description%></p>
        <p><%=@dish.price%></p>
        <p>This dish is <%=@dish.active_?%></p>
      </div>
    </div>
  </div>
</div>